### ISSUE TITLE
[Bug] Radarr not displaying all missing movies

### ISSUE THREAD

**Issue by r0arkin** [JagandeepBrar/LunaSea#10]
**Describe the Bug**
LunaSea doesn't show all the missing movies in Radarr.

**To Reproduce**
I have 32 movies missing currently and only 9 show up.

**Expected Behaviour**
All 32 moves should show up.

**Comment by r0arkin** [comment]
![IMG_0667](https://user-images.githubusercontent.com/46236585/71610025-485b4b80-2b42-11ea-8726-676dae97c39b.png)
<img width="321" alt="Screen Shot 2019-12-30 at 8 22 06 PM" src="https://user-images.githubusercontent.com/46236585/71610029-514c1d00-2b42-11ea-99fb-9180a44d60b1.png">

**Comment by JagandeepBrar** [comment]
Are some of the movies releasing more than 60 days in the future? Right now it only checks for movies that have already been released physically or will be released in the next 31 days (1 month).

I might re-work it to show everything, but I thought it since it was "missing" it should be only releases that are/might be readily available (in the case of a leak, usually happens 1-2 weeks early).

Thoughts?

**Comment by JagandeepBrar** [comment]
Actually, decided to show all releases so it doesn't cause confusion for others in the future.

Fixed in #11.

**Comment by r0arkin** [comment]
Ah got it! I would be okay with any of those options, whatever you think is best. If you were to keep the original way you had it, a popup would have been helpful so there isn’t any confusion! Just a suggestion. But looks like you changed it to show all :)

**Comment by JagandeepBrar** [comment]
Yes! I think it's best to just show all in the end.

I also just merged in changes that makes it also show titles that have been announced, so it should show any titles that are not marked as downloaded regardless of when it is releasing.
