### ISSUE TITLE
[Feature Request] Support Sonarr V3

### ISSUE THREAD

**Issue by theg00s3** [JagandeepBrar/LunaSea#18]
**Describe the solution you'd like**
A toggle switch to connect to a Sonarr V3 instance.
**Additional context**
Sonarr V3 has a different API to Sonarr V2. Ombi has a toggle to switch between the APIs, with the source code [here.](https://github.com/tidusjar/Ombi/tree/master/src/Ombi.Api.Sonarr)

**Comment by JagandeepBrar** [comment]
You mentioned this in #16 before you closed it, I will take a look into this because I believe it should still work but I can take a look to see if there is anything I need to change.

I do want to support all of the new features of V3, I just don't have V3 installed at the moment but I will install it this week and get back to you. Just taking a small break from the project this week to spend some time with friends & family.

**Comment by theg00s3** [comment]
I'm not sure what happened, but the latest update seems to make Sonarr V3 work

**Comment by JagandeepBrar** [comment]
Glad to hear it is working now, not sure what the problem must have been. I will be closing this issue for now then, if another issue arises feel free to re-open this one or open another issue!
