### ISSUE TITLE
[Bug] - Unable to build because ExportOptions.plist is missing

### ISSUE THREAD

**Issue by johntdyer** [JagandeepBrar/LunaSea#26]
**Describe the Bug**
I am getting an error when running build_ipa because its missing ExportOptions.plist

**To Reproduce**
./build_ipa

**Expected Behaviour**
build an api, but I am not really an IOS dev so I haven't any clue whats required for this file... I did notuice you have yours in your .gitignore

**Screenshots**

**Versions**
latest

**Additional context**

**Comment by JagandeepBrar** [comment]
I put together a quick installation guide on the Wiki: https://github.com/JagandeepBrar/LunaSea/wiki/Installation

Step 2 is the place where you set up ExportOptions.plist. I have it in the .gitignore because my local version contains my team ID, and ensured a user sets up the file themselves first. 

If you're still running into problems I can try to help out!

**Comment by johntdyer** [comment]
@JagandeepBrar  thanks, that helped !

**Comment by JagandeepBrar** [comment]
Awesome, going to close this issue then. Leave another comment if you need anymore help!
