### ISSUE TITLE
[Bug] Lost all my config & unable to add a new one

### ISSUE THREAD

**Issue by LacazeThomas** [JagandeepBrar/LunaSea#696]
**Describe the Bug**
After the last update I lost all my configuration. And when add the "host" in the "Connection Details" its stay "not set". Even if a add all parameters and I click on "Test connection"

**To Reproduce**
Update to the latest LunaSea iOS version 

**Screenshots**
https://user-images.githubusercontent.com/19855907/185890388-c5cf54b6-4326-42b8-8711-d7e3a6d42932.MOV

**Versions**
10.1.1

**Comment by JagandeepBrar** [comment]
Hi @LacazeThomas,

The lost configuration occurred because of a database corruption. Apologies for that but clearing the configuration is the only way to remedy this as the profiles are unable to be loaded once the stricter type checking on the profiles was implemented.

As for the inability to re-add your config, can you please try re-installing the application? This is a very rare bug that can occur. Another option is to open your Files application -> On my iPhone -> LunaSea and delete the `database` folder.

Apologies again for the lost configuration but the stricter type checks on the database are in-place to prevent further problems in the future and should not occur again.
