### ISSUE TITLE
[Bug] Cannot copy webhook url (Android)

### ISSUE THREAD

**Issue by Flash1232** [JagandeepBrar/LunaSea#713]
**Describe the Bug**
When I go under Settings>Notifications>Overseerr and click the Device button (or any other option) nothing happens and I get no webhook into my clipboard.

**To Reproduce**
As above.

**Expected Behaviour**
I should have the webhook url in clipboard.

**Screenshots**

**Versions**
10.2.0 stable

**Additional context**

**Comment by JagandeepBrar** [comment]
Does your device have Google Play Services installed?

**Comment by Flash1232** [comment]
No, it does not.

**Comment by JagandeepBrar** [comment]
Sorry for the very late response, been dealing with a move and a few other things lately in my personal life!

Google Play Services are required for notifications to work, and so by extension you will not be able to copy the webhook URLs without them installed. This is because notifications currently rely on [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) which relies on Google play Services.

I will try to add in detection of Google Play Services and hide the notifications section on devices without it, but at this time there are no alternatives with Flutter except for OneSignal which also uses Firebase Cloud Messaging under the hood.

So at this time it is not possible to receive notifications on Android with GPS installed.

**Comment by Flash1232** [comment]
No worries and thanks for the clarification.

I have no dev experience with Flutter but it seems unifiedpush might be supported: https://unifiedpush.org/developers/flutter/
