### ISSUE TITLE
[Feature Request] Sonarr - Individual Episode Deletion & Series Initial Monitored Status

### ISSUE THREAD

**Issue by grizzlechips** [JagandeepBrar/LunaSea#72]
I noticed that there is a File Management option (trash can button) for Radarr movie files, but I haven't been able to find a similar button for individual episodes of a show on Sonarr:

![image](https://user-images.githubusercontent.com/6484738/73199479-883e3000-40fa-11ea-947e-144118b40fa8.png)

Also, when adding a series, Sonarr lets you set the initial monitored state (Future, Latest Season, First Season, None, etc.), and I haven't been able to locate that either.  This is a pretty important step that I'd love to see added, as well.

**Comment by JagandeepBrar** [comment]
On the file deletion: I wanted to avoid file management as much as possible within the app, but I can add this functionality behind a long press of the episode card.

On the series adding: I couldn't figure out what the API call value is for setting those preferences, since it is not obvious on the [Sonarr API documentation](https://github.com/Sonarr/Sonarr/wiki/Series#post), but I'll try to experiment with it and get a result.

**Comment by grizzlechips** [comment]
I understand the hesitance.  I can't speak for everyone, but such a large part of how I use Sonarr is file management, especially when it comes to different versions of episodes - e.g. Subbed, Commentary, Quality Profiles, or just straight up incorrectly-named uploads - that having access to these functions could, I think, really bring the app closer to a full mobile solution.

**Comment by JagandeepBrar** [comment]
I am going to push this back for the time being, since I haven't found a clean way to add in deletion. I want to really ensure that no user accidentally deletes their data, so I am trying to find somewhere that it's relatively hidden.

I also couldn't find a way through the API to set the initial state, so I will have to hack together an on-device way of doing it. I will also be adding this in a future release (not v1.0.0), but soon for sure.

**Comment by JagandeepBrar** [comment]
The first part of this (individual episode deletion) is now merged into `v1.1.0`, it will be in the next release and in TestFlight soon!

For the second part, you can follow this issue instead: https://github.com/JagandeepBrar/LunaSea/issues/113
