### ISSUE TITLE
[Feature Request] Implement the speed limit feature in Nzbget

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#75]
Great job on the app by the way, I'm only opening all these requests to help make the app better :)

At the moment I use an app called NZBClient which has some cool features you could probably poach. The Speed Limit is something I use a bit to avoid saturating bandwidth.

**Comment by JagandeepBrar** [comment]
I really appreciate all the feedback! It only helps it become a better product :)

For this though, it's already implemented! I know that I need to add some kind of tutorial/guide because I feel like lots of functionality is hidden behind unknown places, but if you tap the "status" section in the app bar (the "idle"/"paused", with speed and time remaining) you will get a prompt to set a speed limit.

The screenshot is from SABnzbd but NZBGet contains this functionality as well:

![IMG_0734](https://user-images.githubusercontent.com/3048295/73218214-247a2e00-411f-11ea-87e0-ad641cd0f4df.png)

**Comment by simonk83** [comment]
Oh right! Maybe there’s a bit of a bug with Nzbget then, I don’t seem to see this:

![6BB98596-DF29-4CA6-8AC4-A27629CFB038](https://user-images.githubusercontent.com/518440/73218524-3a82ff80-41ae-11ea-9138-a942ec504263.jpeg)
