### ISSUE TITLE
[Bug] Error adding show to Sonarr

### ISSUE THREAD

**Issue by kaladinsb0** [JagandeepBrar/LunaSea#753]
**Describe the Bug**
When trying to add a show to Sonarr an error occurs.

**To Reproduce**
Open LunaSea. Goto Sonarr. Add a show.

**Expected Behaviour**
It's never worked so I assume the show just adds.

**Screenshots**

**Versions**
The latest version of LunaSea (but this feature hasn't worked since I installed it, I think two versions ago). Latest version of Sonarr as well.

**Additional context**
This is the error:

type '_GrowableList<dynamic>' is not a subtype of type 'Map<String, dynamic>'

**Comment by JagandeepBrar** [comment]
This occurs because you have your host incorrectly set up and the host is currently redirecting. Redirects work with fetching data (GET requests) but will not work for sending data back to the machine (POST/PUT requests).

Take a look at the docs here: https://docs.lunasea.app/modules/sonarr#host

The key thing that was likely forgotten was the URL base, please ensure that it was appended to the host. If you are unable to find the correct URL, you can also load the web GUI on your mobile device and copy and use the host when viewing the main library/homepage of Sonarr.

**Comment by exalented** [comment]
The check passes without the URL Base set, so this should be changed.
