### ISSUE TITLE
[Bug] SABnzbd config test fails with connection error

### ISSUE THREAD

**Issue by ianweatherburn** [JagandeepBrar/lunasea#761]
SABnzbd on Docker ([ghcr.io/jagandeepbrar/lunasea:beta])) fails with:
_DioError [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer._
at the "Test Connect" screen.

The configuration is exactly the same as Lunasea setup on iOS which works correctly.
All other configs to Sonarr/Radarr etc work correctly from your Lunasea docker (with all of these components running on a docker default network 172.18.0.0/24)

SABnzbd config in Lunasea is setup as:
http://192.168.0.xxx:8080 
with the correct API key (which works on iOS app)
_Have also tried with the IP of the docker container (172.18.0.14:8080)_

SABnzbd security for external access is setup as 
Full Web Interface (only external access requires login)

Have tried with a Basic Auth header using the SABnzbd credentials, no difference.

**Comment by JagandeepBrar** [comment]
Is your SABnzbd or LunaSea hosted instance utilizing HTTPS/SSL?

**Comment by ianweatherburn** [comment]
Both Lunasea and SABnzbd are on http and not https

**Comment by JagandeepBrar** [comment]
Sadly due to the way that Flutter compiles to web, I can't get more details about why the network call is failing.

All I can suggest is to take another look at the host and API key and validate everything looks good, maybe even try restoring from a backup of a device that can for sure connect.

I was able to confirm that it's not a direct issue with LunaSea as I am able to connect both via my local IP and my reverse proxy host using the web GUI via the hosted and self-hosted versions.

**Comment by JagandeepBrar** [comment]
For now I am going to close the ticket as a support ticket, if you need some additional help reach out via one of the channels mentioned by the bot.
